spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5142/Gestionale
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 3001